### ISSUE TITLE
Support Version 8 of the HLS specification

### ISSUE THREAD

**Issue by dcoufal** [Comcast/mamba#4]
### Description

Ideally, mamba would support all HLS tags through version 8.

This issue is more of a epic, and each tag would be a specific sub issue. If you decide to peel off a unsupported tag, make a new issue and link back to this one.

### Tasks

For each tag

- [ ] Add the tag to `PantosTag`
- [ ] Add any data keys needed for the tag in `PantosValue`
- [ ] Add a new `HLSTagValidator` if needed.

### References

* Preliminary spec available at https://developer.apple.com/streaming/HLS-WWDC-2017-Preliminary-Spec.pdf

* Older HLS specs available at https://tools.ietf.org/html/draft-pantos-http-live-streaming-23
