### ISSUE TITLE
The `playlistType` for a variant playlist should be cached and not calculated every time.

### ISSUE THREAD

**Issue by dcoufal** [Comcast/mamba#41]
### Description

Right now, if you call `playlistType` for a playlist, the type is calculated every time from scratch. It's a small calculation, but it's not uncommon in Comcast code to call this a lot.

It should be cached. The cached value should clear if the playlist is edited.

Depends on <https://github.com/Comcast/mamba/issues/5>

### Tasks

- [ ] Have a `private` cached version of `playlistType`. Calls to public `playlistType` should check if there's a cache and return it.
- [ ] The cache should probably live in `PlaylistStructure` since, if the playlist is edited, the cache value should clear.
- [ ] Shouldn't be a `unknown` type anymore since we know we are a variant and therefore have rules about determination of `playlistType` that are always applicable.

**Comment by dcoufal** [comment]
Addressed
